# Task-pandas

## Preprocessing

### Import libraries

In [4]:
import pandas as pd
import time as t
import warnings as w

### Timestamp

In [3]:
t.asctime()

'Thu Jul 23 12:29:52 2026'

### Ignore warnings

In [5]:
w.filterwarnings('ignore')

### Load Dataset

In [8]:
df=pd.read_csv('sample_data_with_nulls.csv')
df.head()

   id      name   age    salary   department
0   1  Person_1  56.0   32695.0      Finance
1   2  Person_2  46.0   78190.0        Sales
2   3       NaN  32.0       NaN        Sales
3   4  Person_4  60.0  117538.0          NaN
4   5  Person_5  25.0   69504.0  Engineering

## Solution

* Drop all rows that contain at least one null value and report how many rows remain.
* Fill missing values in the age column with the mean age, and missing values in salary with the median salary.
* Fill missing values in the department column with the mode (most frequent department).
* Group the data by department and calculate the average salary for each group (ignoring nulls).
* Find all rows where age is greater than 40 and salary is above 80,000.
* Sort the DataFrame by salary in descending order and display the top 10 records.
* Create a new column salary_category that labels each row as "Low" (<50,000), "Medium" (50,000–90,000), or "High" (>90,000) based on the salary column, handling nulls appropriately.

### Drop all rows that contain at least one null value and report how many rows remain.

In [10]:
df_no_null = df.dropna()

print("Rows remaining:", len(df_no_null))
df_no_null.head()

Rows remaining: 67

   id      name   age   salary   department
0   1  Person_1  56.0  32695.0      Finance
1   2  Person_2  46.0  78190.0        Sales
4   5  Person_5  25.0  69504.0  Engineering
7   8  Person_8  36.0  91858.0  Engineering
8   9  Person_9  40.0  42666.0           HR

### Fill missing values in the age column with the mean age, and missing values in salary with the median salary.

In [11]:
df['age'] = df['age'].fillna(df['age'].mean())
df['salary'] = df['salary'].fillna(df['salary'].median())
df.head()

   id      name   age    salary   department
0   1  Person_1  56.0   32695.0      Finance
1   2  Person_2  46.0   78190.0        Sales
2   3       NaN  32.0   78190.0        Sales
3   4  Person_4  60.0  117538.0          NaN
4   5  Person_5  25.0   69504.0  Engineering

### Fill missing values in the department column with the mode (most frequent department).

In [12]:
df['department'] = df['department'].fillna(df['department'].mode()[0])
df.head()

   id      name   age    salary   department
0   1  Person_1  56.0   32695.0      Finance
1   2  Person_2  46.0   78190.0        Sales
2   3       NaN  32.0   78190.0        Sales
3   4  Person_4  60.0  117538.0        Sales
4   5  Person_5  25.0   69504.0  Engineering

### Group the data by department and calculate the average salary for each group (ignoring nulls).

In [13]:
avg_salary = df.groupby('department')['salary'].mean()
print(avg_salary)

department
Engineering    79182.000000
Finance        67687.666667
HR             73971.380952
Marketing      72247.782609
Sales          79848.781250
Name: salary, dtype: float64

### Find all rows where age is greater than 40 and salary is above 80,000.

In [15]:
result = df[(df['age'] > 40) & (df['salary'] > 80000)]
print(result)

    id       name       age    salary   department
3    4   Person_4  60.00000  117538.0        Sales
12  13  Person_13  53.00000   94505.0      Finance
13  14  Person_14  57.00000   82251.0           HR
17  18  Person_18  40.88764  108603.0        Sales
18  19  Person_19  41.00000   82256.0           HR
21  22  Person_22  55.00000  107373.0    Marketing
24  25  Person_25  50.00000   93335.0    Marketing
27  28  Person_28  61.00000  100592.0  Engineering
29  30  Person_30  44.00000  109309.0    Marketing
31  32  Person_32  45.00000   82992.0           HR
35  36  Person_36  61.00000  117054.0        Sales
41  42  Person_42  56.00000  117939.0        Sales
43  44  Person_44  40.88764  110356.0           HR
44  45  Person_45  42.00000  101910.0  Engineering
50  51  Person_51  45.00000  111734.0        Sales
51  52        NaN  64.00000  105450.0           HR
72  73  Person_73  53.00000   91373.0  Engineering
74  75  Person_75  40.88764   85016.0  Engineering
76  77  Person_77  40.88764   88053.0      Finance
85  86  Person_86  41.00000   98840.0        Sales
86  87  Person_87  43.00000   84384.0        Sales
87  88        NaN  40.88764   81005.0           HR
90  91  Person_91  46.00000   92003.0      Finance
92  93        NaN  62.00000   82733.0    Marketing
94  95  Person_95  42.00000  119474.0  Engineering
97  98        NaN  41.00000  115616.0           HR

### Sort the DataFrame by salary in descending order and display the top 10 records.

In [17]:
top10 = df.sort_values(by='salary', ascending=False)
top10.head(10)

    id       name   age    salary   department
94  95  Person_95  42.0  119474.0  Engineering
41  42  Person_42  56.0  117939.0        Sales
36  37  Person_37  20.0  117897.0    Marketing
3    4   Person_4  60.0  117538.0        Sales
35  36  Person_36  61.0  117054.0        Sales
97  98        NaN  41.0  115616.0           HR
23  24  Person_24  38.0  114651.0           HR
91  92  Person_92  32.0  113211.0    Marketing
32  33  Person_33  33.0  112948.0        Sales
50  51  Person_51  45.0  111734.0        Sales

### Create a new column salary_category that labels each row as "Low" (<50,000), "Medium" (50,000–90,000), or "High" (>90,000) based on the salary column, handling nulls appropriately.

In [21]:
def salary_category(salary):
    if pd.isna(salary):
        return "Missing"
    elif salary < 50000:
        return "Low"
    elif salary <= 90000:
        return "Medium"
    else:
        return "High"
        
df['salary_category'] = df['salary'].apply(salary_category)
df[['salary', 'salary_category']].head()

     salary salary_category
0   32695.0             Low
1   78190.0          Medium
2   78190.0          Medium
3  117538.0            High
4   69504.0          Medium